import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { Graph } from '../components/graph'

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Collatz Conjecture Graph</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Graph />
			</main>
		</div>
	)
}

export default Home
