import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { CollatzGraph } from '../components/collatz-graph'

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Collatz Conjecture Graph</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1>Collatz Graph</h1>
				<CollatzGraph />
			</main>
		</div>
	)
}

export default Home
