import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import React from 'react'
import CollatzGraph from '../components/collatz'
import FibonacciGraph from '../components/fibonacci'

const Home: NextPage = () => {
	let [sequence, setSequence] = React.useState('collatz')

	return (
		<div className={styles.container}>
			<Head>
				<title>Sequences Graphs</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className="input-wrapper">
					<label htmlFor="sequence-type-value">Sequence : </label>
					<select id="sequence-type-value" onChange={e => setSequence(e.target.value)}>
						<option value="collatz">Collatz</option>
						<option value="fibonacci">Fibonacci</option>
					</select>
				</div>
				{sequence === 'collatz' && <CollatzGraph />}
				{sequence === 'fibonacci' && <FibonacciGraph />}
			</main>
		</div>
	)
}

export default Home